// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           int64                  `protobuf:"varint,1,opt,name=Bid,proto3" json:"Bid,omitempty"`
	Ls            int64                  `protobuf:"varint,2,opt,name=ls,proto3" json:"ls,omitempty"`
	ClientId      int64                  `protobuf:"varint,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidIn) Reset() {
	*x = BidIn{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidIn) ProtoMessage() {}

func (x *BidIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidIn.ProtoReflect.Descriptor instead.
func (*BidIn) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *BidIn) GetBid() int64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *BidIn) GetLs() int64 {
	if x != nil {
		return x.Ls
	}
	return 0
}

func (x *BidIn) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type BidAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           string                 `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	Ls            int64                  `protobuf:"varint,2,opt,name=ls,proto3" json:"ls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidAck) Reset() {
	*x = BidAck{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidAck) ProtoMessage() {}

func (x *BidAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidAck.ProtoReflect.Descriptor instead.
func (*BidAck) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *BidAck) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

func (x *BidAck) GetLs() int64 {
	if x != nil {
		return x.Ls
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

type ResultOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HighestBid    int64                  `protobuf:"varint,1,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultOut) Reset() {
	*x = ResultOut{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultOut) ProtoMessage() {}

func (x *ResultOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultOut.ProtoReflect.Descriptor instead.
func (*ResultOut) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *ResultOut) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

type ImAlive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImAlive) Reset() {
	*x = ImAlive{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImAlive) ProtoMessage() {}

func (x *ImAlive) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImAlive.ProtoReflect.Descriptor instead.
func (*ImAlive) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

func (x *ImAlive) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type DataBackup struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HighestBid        int64                  `protobuf:"varint,1,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	Ls                int64                  `protobuf:"varint,2,opt,name=ls,proto3" json:"ls,omitempty"`
	AuctionGoing      bool                   `protobuf:"varint,3,opt,name=auctionGoing,proto3" json:"auctionGoing,omitempty"`
	TimeLeftOfAuction int64                  `protobuf:"varint,4,opt,name=timeLeftOfAuction,proto3" json:"timeLeftOfAuction,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DataBackup) Reset() {
	*x = DataBackup{}
	mi := &file_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBackup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBackup) ProtoMessage() {}

func (x *DataBackup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBackup.ProtoReflect.Descriptor instead.
func (*DataBackup) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{5}
}

func (x *DataBackup) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *DataBackup) GetLs() int64 {
	if x != nil {
		return x.Ls
	}
	return 0
}

func (x *DataBackup) GetAuctionGoing() bool {
	if x != nil {
		return x.AuctionGoing
	}
	return false
}

func (x *DataBackup) GetTimeLeftOfAuction() int64 {
	if x != nil {
		return x.TimeLeftOfAuction
	}
	return 0
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"E\n" +
	"\x05BidIn\x12\x10\n" +
	"\x03Bid\x18\x01 \x01(\x03R\x03Bid\x12\x0e\n" +
	"\x02ls\x18\x02 \x01(\x03R\x02ls\x12\x1a\n" +
	"\bclientId\x18\x03 \x01(\x03R\bclientId\"*\n" +
	"\x06BidAck\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\tR\x03ack\x12\x0e\n" +
	"\x02ls\x18\x02 \x01(\x03R\x02ls\"\a\n" +
	"\x05Empty\"+\n" +
	"\tResultOut\x12\x1e\n" +
	"\n" +
	"highestBid\x18\x01 \x01(\x03R\n" +
	"highestBid\"\x1b\n" +
	"\aimAlive\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\"\x8e\x01\n" +
	"\n" +
	"DataBackup\x12\x1e\n" +
	"\n" +
	"highestBid\x18\x01 \x01(\x03R\n" +
	"highestBid\x12\x0e\n" +
	"\x02ls\x18\x02 \x01(\x03R\x02ls\x12\"\n" +
	"\fauctionGoing\x18\x03 \x01(\bR\fauctionGoing\x12,\n" +
	"\x11timeLeftOfAuction\x18\x04 \x01(\x03R\x11timeLeftOfAuction2\x87\x01\n" +
	"\aAuction\x12\x16\n" +
	"\x03Bid\x12\x06.BidIn\x1a\a.BidAck\x12\x1c\n" +
	"\x06Result\x12\x06.Empty\x1a\n" +
	".ResultOut\x12\x1d\n" +
	"\tHeartBeat\x12\x06.Empty\x1a\b.imAlive\x12'\n" +
	"\x10BackUpToReplicas\x12\v.DataBackup\x1a\x06.EmptyB\x18Z\x16Replication/grpc/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_proto_goTypes = []any{
	(*BidIn)(nil),      // 0: BidIn
	(*BidAck)(nil),     // 1: BidAck
	(*Empty)(nil),      // 2: Empty
	(*ResultOut)(nil),  // 3: ResultOut
	(*ImAlive)(nil),    // 4: imAlive
	(*DataBackup)(nil), // 5: DataBackup
}
var file_proto_proto_depIdxs = []int32{
	0, // 0: Auction.Bid:input_type -> BidIn
	2, // 1: Auction.Result:input_type -> Empty
	2, // 2: Auction.HeartBeat:input_type -> Empty
	5, // 3: Auction.BackUpToReplicas:input_type -> DataBackup
	1, // 4: Auction.Bid:output_type -> BidAck
	3, // 5: Auction.Result:output_type -> ResultOut
	4, // 6: Auction.HeartBeat:output_type -> imAlive
	2, // 7: Auction.BackUpToReplicas:output_type -> Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
